print('hello python & git rock')
print('test the add')
print('test add message in original python file')
print('add message in github for testing')
print('final test for git')
print('some test for github')
print('test from peter')
print('test from peter in github for pull')
print('final check pull & push')

